# Generated by Django 4.2.2 on 2023-06-16 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comments_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watched_by',
        ),
        migrations.AddField(
            model_name='listing',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
